In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.1'

## Create & Read

#### 1D Array

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [9]:
arr1.size

5

#### 2D Array

In [10]:
arr2 = np.array([[1, 2, 6], [3, 4, 8]])

In [11]:
type(arr2)

numpy.ndarray

In [12]:
arr2.dtype

dtype('int64')

In [13]:
arr2.shape

(2, 3)

In [14]:
arr2.ndim

2

In [15]:
arr2.size

6

#### 3D Array

In [16]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
type(arr3)

numpy.ndarray

In [18]:
arr3.dtype

dtype('int64')

In [19]:
arr3.shape

(2, 3, 3)

In [20]:
arr3.size

18

In [21]:
arr3.ndim

3

## Create Random Array

In [27]:
randomArr = np.random.rand(2, 3, 3)
randomArr

array([[[0.79618598, 0.12485997, 0.85675738],
        [0.51111901, 0.34625845, 0.12497461],
        [0.89827905, 0.01064402, 0.12407996]],

       [[0.92662152, 0.98042499, 0.1242072 ],
        [0.21089555, 0.85275269, 0.73372231],
        [0.46777324, 0.08291541, 0.55348193]]])

In [28]:
randomArr.dtype

dtype('float64')

In [92]:
zeroes = np.zeros((3, 2, 3))

In [93]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [94]:
zeroes.ndim

3

In [95]:
full = np.full((6, 2, 3), 3)

In [96]:
full

array([[[3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]]])

In [97]:
full[0, 0]

array([3, 3, 3])

In [98]:
full[2]

array([[3, 3, 3],
       [3, 3, 3]])

In [99]:
full[5]

array([[3, 3, 3],
       [3, 3, 3]])

In [100]:
randomArr[1]

array([[0.92662152, 0.98042499, 0.1242072 ],
       [0.21089555, 0.85275269, 0.73372231],
       [0.46777324, 0.08291541, 0.55348193]])

In [101]:
randomArr[1, 1, 2]

np.float64(0.7337223127548247)

In [102]:
randomArr[0:1]

array([[[0.79618598, 0.12485997, 0.85675738],
        [0.51111901, 0.34625845, 0.12497461],
        [0.89827905, 0.01064402, 0.12407996]]])

In [103]:
randomArr[-1]

array([[0.92662152, 0.98042499, 0.1242072 ],
       [0.21089555, 0.85275269, 0.73372231],
       [0.46777324, 0.08291541, 0.55348193]])

## Update and Delete

In [104]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [105]:
a1

array([[[0.91510206, 0.68595991],
        [0.3750628 , 0.30303702],
        [0.98354914, 0.41517183]],

       [[0.42699026, 0.73529815],
        [0.31279693, 0.67595259],
        [0.18817473, 0.32798496]]])

In [106]:
a2

array([[[0.54703263, 0.96595929],
        [0.3487392 , 0.31996712],
        [0.72844713, 0.21446996]],

       [[0.61829422, 0.63823822],
        [0.79047427, 0.28057501],
        [0.04085152, 0.35139706]]])

#### Basic Math Operations

In [107]:
np.add(a1, a2)

array([[[1.46213469, 1.65191921],
        [0.72380199, 0.62300414],
        [1.71199627, 0.62964178]],

       [[1.04528447, 1.37353637],
        [1.1032712 , 0.9565276 ],
        [0.22902626, 0.67938202]]])

In [108]:
np.subtract(a1, a2)

array([[[ 0.36806943, -0.27999938],
        [ 0.0263236 , -0.0169301 ],
        [ 0.255102  ,  0.20070187]],

       [[-0.19130396,  0.09705993],
        [-0.47767734,  0.39537759],
        [ 0.14732321, -0.0234121 ]]])

In [109]:
np.divide(a1, a2)

array([[[1.67284731, 0.71013335],
        [1.07548219, 0.94708799],
        [1.35019975, 1.93580414]],

       [[0.69059397, 1.15207477],
        [0.39570792, 2.40916896],
        [4.6063089 , 0.93337422]]])

In [110]:
np.multiply(a1, a2)

array([[[0.50059069, 0.66260935],
        [0.1307991 , 0.09696188],
        [0.71646355, 0.08904188]],

       [[0.26400561, 0.46929538],
        [0.24725793, 0.1896554 ],
        [0.00768722, 0.11525295]]])

In [111]:
sqrt = np.sqrt(26)
abs = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [112]:
sqrt

np.float64(5.0990195135927845)

In [113]:
abs

np.int64(2)

In [114]:
power

np.int64(256)

In [115]:
log

np.float64(3.2188758248682006)

In [116]:
mins

np.float64(0.1881747328212683)

In [117]:
maxs

np.float64(0.9659592948799334)

#### Update

In [118]:
a3 = np.random.rand(2, 3, 3)

In [119]:
a3

array([[[0.48368136, 0.43331259, 0.83597884],
        [0.48794986, 0.41342436, 0.11984859],
        [0.98112672, 0.80865811, 0.3645576 ]],

       [[0.31709631, 0.87871287, 0.65933685],
        [0.05888066, 0.42213612, 0.6927875 ],
        [0.02814739, 0.81967425, 0.8608236 ]]])

In [120]:
a3[0, 1, 2] = 1

In [121]:
a3

array([[[0.48368136, 0.43331259, 0.83597884],
        [0.48794986, 0.41342436, 1.        ],
        [0.98112672, 0.80865811, 0.3645576 ]],

       [[0.31709631, 0.87871287, 0.65933685],
        [0.05888066, 0.42213612, 0.6927875 ],
        [0.02814739, 0.81967425, 0.8608236 ]]])

In [122]:
a3.sort()
a3

array([[[0.43331259, 0.48368136, 0.83597884],
        [0.41342436, 0.48794986, 1.        ],
        [0.3645576 , 0.80865811, 0.98112672]],

       [[0.31709631, 0.65933685, 0.87871287],
        [0.05888066, 0.42213612, 0.6927875 ],
        [0.02814739, 0.81967425, 0.8608236 ]]])

In [123]:
a3_reshape = a3.reshape((3, 2, 3))
a3_reshape

array([[[0.43331259, 0.48368136, 0.83597884],
        [0.41342436, 0.48794986, 1.        ]],

       [[0.3645576 , 0.80865811, 0.98112672],
        [0.31709631, 0.65933685, 0.87871287]],

       [[0.05888066, 0.42213612, 0.6927875 ],
        [0.02814739, 0.81967425, 0.8608236 ]]])

### Appending & Inserting

In [139]:
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [140]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [141]:
appd = np.append(zeroes, new_array, axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [148]:
insert_array = np.insert(zeroes, 1, new_array, axis=0)
insert_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [169]:
arr4 = np.random.rand(3, 2, 3)

In [170]:
arr4

array([[[0.72263361, 0.61034851, 0.16824316],
        [0.31044558, 0.75378653, 0.62704066]],

       [[0.56552298, 0.78981486, 0.03846256],
        [0.82704974, 0.80840083, 0.93695196]],

       [[0.70763866, 0.91773018, 0.90054495],
        [0.26137738, 0.21660065, 0.19968555]]])

In [177]:
arr5 = np.delete(arr4, 0, axis=1)

In [180]:
np.save('new_array', arr5)

In [183]:
np.load('new_array.npy')

array([[[0.31044558, 0.75378653, 0.62704066]],

       [[0.82704974, 0.80840083, 0.93695196]],

       [[0.26137738, 0.21660065, 0.19968555]]])